theme = "ao"

[editor]
line-number = "relative"
bufferline = "always"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
# left = ["mode", "spinner"]
# center = ["file-name"]
# right = [
#   "diagnostics",
#   "selections",
#   "position",
#   "file-encoding",
#   "file-line-ending",
#   "file-type",
# ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-o = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]
C-u = "redo"
tab = ":buffer-next"
S-tab = ":buffer-previous"
C-q = ":buffer-close"
C-g = [":new", ":insert-output lazygit", ":buffer-close", ":redraw"]
C-f = ":sh tmux new-window -n fx '~/.config/helix/yazi-picker.sh open'"     # WARN: MUST BE IN TMUX SESSION !!! otherwise won't be work
D = ["goto_line_start", "select_mode", "goto_line_end", "delete_selection"]
S-a = "select_all"
