theme = "sonokai"

[editor]
line-number = "relative"
bufferline = "always"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
# left = ["mode", "spinner"]
# center = ["file-name"]
# right = [
#   "diagnostics",
#   "selections",
#   "position",
#   "file-encoding",
#   "file-line-ending",
#   "file-type",
# ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[keys.normal]
C-u = "redo"
tab = ":buffer-next"
S-tab = ":buffer-previous"
C-q = ":buffer-close"
