theme = "ao"

[editor]
line-number = "relative"
bufferline = "always"
mouse = true
cursorline = true
cursorcolumn = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

# https://docs.helix-editor.com/master/configuration.html#editorsoft-wrap-section
[editor.soft-wrap]
enable = true
# wrap-at-text-width = true
wrap-indicator = "↩ "

### https://docs.helix-editor.com/master/configuration.html#editorwhitespace-section
[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)
### 

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name", "separator", "version-control", "separator"]
right = ["position", "position-percentage", "total-line-numbers"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-o = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]
C-r = "redo"
tab = ":buffer-next"
S-tab = ":buffer-previous"
C-q = ":buffer-close"
C-g = [":new", ":insert-output lazygit", ":buffer-close", ":redraw"]
C-f = ":sh tmux new-window -n fx '~/.config/helix/yazi-picker.sh open'"     # WARN: MUST BE IN TMUX SESSION !!! otherwise won't be work
D = ["goto_line_start", "select_mode", "goto_line_end", "delete_selection"]
S-a = "select_all"
V = ["goto_line_start", "select_mode", "goto_line_end"]
"G" = "goto_file_end"
"g" = { "g" = "goto_file_start" }
"K" = "hover"
C-k = "keep_selections"
C-s = ":w"
S-h = "goto_line_start"
S-l = "goto_line_end"
C-d = "page_down"
C-u = "page_up"
